# Generated by Django 3.2.25 on 2024-06-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
