# Generated by Django 3.2.25 on 2024-06-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=100)),
                ('script', models.CharField(default='', max_length=700)),
                ('preco', models.FloatField(default=0.0)),
                ('expira_em', models.DateTimeField(default=None)),
            ],
        ),
    ]
