# Generated by Django 3.2.25 on 2024-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacote', '0002_alter_pacote_expira_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacote',
            name='device_limit',
            field=models.IntegerField(default=1),
        ),
    ]
