# Generated by Django 3.2.25 on 2024-06-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Router', '__first__'),
        ('Compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('radius_user', models.CharField(default='', max_length=300)),
                ('device', models.CharField(default='', max_length=700)),
                ('expira_em', models.DateTimeField(default=None)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compra.compra')),
                ('id_rooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Router.router')),
            ],
        ),
    ]
