# Generated by Django 3.2.25 on 2024-06-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Router', '__first__'),
        ('Pacote', '0001_initial'),
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('radius_user', models.CharField(default='', max_length=300)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
                ('id_pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacote.pacote')),
                ('id_rooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Router.router')),
            ],
        ),
    ]
