# Generated by Django 3.2.25 on 2024-06-08 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Router', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=300)),
                ('id_rooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Router.router')),
            ],
        ),
    ]
