# Generated by Django 3.2.25 on 2024-06-30 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pacote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='', max_length=12)),
                ('preco', models.FloatField(default=0.0)),
                ('is_valid', models.BooleanField(default=True)),
                ('id_pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pacote.pacote')),
            ],
        ),
    ]
