# Generated by Django 3.2.25 on 2024-06-30 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recarga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recarga',
            name='code',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
